@EnterpriseKnowledge.Api_HostAddress = https://localhost:7126
@host = https://localhost:7126

POST {{host}}/api/documents
Content-Type: application/json

{
  "fileName": "security-policy.pdf",
  "contentType": "application/pdf",
  "sizeInBytes": 1024
}



